apiVersion: v1
kind: Service
metadata:
  name: drone-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: drone
    component: server
  type: NodePort
